"""
Pydantic schemas for Resume generation features.
"""
from pydantic import BaseModel, HttpUrl, Field
from typing import Optional, List
from datetime import datetime


# ============================================================================
# Input Schemas
# ============================================================================

class GenerateResumeRequest(BaseModel):
    """Request to generate an ATS-optimized resume."""
    job_id: int = Field(..., description="Job application ID")


# ============================================================================
# Profile Component Schemas (for aggregated user data)
# ============================================================================

class ProfileBasicInfo(BaseModel):
    """Basic user information for resume."""
    first_name: str
    last_name: str
    email: str
    phone: Optional[str] = None
    summary: Optional[str] = None
    
    class Config:
        from_attributes = True


class ProfileSkill(BaseModel):
    """User skill entry."""
    skill_name: str
    skill_type: str
    
    class Config:
        from_attributes = True


class ProfileSocialLink(BaseModel):
    """Social link entry."""
    platform: str
    url: str
    
    class Config:
        from_attributes = True


class ProfileProject(BaseModel):
    """User project entry."""
    title: str
    description: Optional[str] = None
    tech_stack: Optional[str] = None
    github_url: Optional[str] = None

    class Config:
        from_attributes = True


class ProfileExperience(BaseModel):
    """User work experience entry."""
    company_name: str
    role: str
    duration: Optional[str] = None
    description: Optional[str] = None

    class Config:
        from_attributes = True


class ProfileEducation(BaseModel):
    """User education entry."""
    college: str
    degree: str
    year: Optional[int] = None

    class Config:
        from_attributes = True


class ProfileCertification(BaseModel):
    """User certification entry."""
    title: str
    issuer: str
    issue_date: Optional[str] = None
    credential_id: Optional[str] = None
    credential_url: Optional[str] = None

    class Config:
        from_attributes = True


class AggregatedUserProfile(BaseModel):
    """Complete aggregated user profile for resume generation."""
    basic_info: ProfileBasicInfo
    skills: List[ProfileSkill] = []
    social_links: List[ProfileSocialLink] = []
    projects: List[ProfileProject] = []
    experience: List[ProfileExperience] = []
    education: List[ProfileEducation] = []
    certifications: List[ProfileCertification] = []


# ============================================================================
# AI-Generated Resume Schema
# ============================================================================

class GeneratedProject(BaseModel):
    """Project section in generated resume."""
    title: str
    github_url: Optional[str] = None
    description: List[str]  # bullet points


class GeneratedExperience(BaseModel):
    """Experience section in generated resume."""
    company_name: str
    role: str
    duration: Optional[str] = None
    description: List[str]  # bullet points


class GeneratedEducation(BaseModel):
    """Education section in generated resume."""
    college: str
    degree: str
    year: Optional[int] = None



class GeneratedCertification(BaseModel):
    """Certification section in generated resume."""
    title: str
    issuer: str
    issue_date: Optional[str] = None


class ATSOptimizedResume(BaseModel):
    """ATS-optimized resume generated by AI."""
    summary: str
    skills: List[str] = []
    projects: List[GeneratedProject] = []
    experience: List[GeneratedExperience] = []
    education: List[GeneratedEducation] = []
    certifications: List[GeneratedCertification] = []


# ============================================================================
# Response Schemas
# ============================================================================

class ResumeGenerationResponse(BaseModel):
    """Response from resume generation endpoint."""
    job_id: int
    company_name: str
    job_title: str
    resume: ATSOptimizedResume
    generated_at: datetime
    
    class Config:
        from_attributes = True


class ResumePreviewResponse(BaseModel):
    """Response for resume preview endpoint."""
    job_id: int
    company_name: str
    job_title: str
    resume: Optional[ATSOptimizedResume] = None
    message: str  # e.g., "No resume generated yet"
    
    class Config:
        from_attributes = True


class ResumePDFResponse(BaseModel):
    """Metadata response for PDF download endpoint."""
    job_id: int
    status: str
    message: str
